### ISSUE TITLE
sunion() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/kinto#128]
https://app.getsentry.com/mozilla/kinto-dev/group/71399462/
```
"PUT   /v1/buckets/newyork" ? (? ms) sunion() takes at least 2 arguments (1 given) lang=None; exception=Traceback (most recent call last):
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/config/views.py", line 243, in _secured_view
    result = _permitted(context, request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/config/views.py", line 241, in _permitted
    permission)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/authorization.py", line 46, in permits
    get_bound_permissions=self.get_bound_permissions)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/permission/__init__.py", line 112, in check_permission
    object_id, permission, get_bound_permissions)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/storage/redis.py", line 18, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/permission/redis.py", line 90, in object_permission_authorized_principals
    return self._decode_set(self._client.sunion(*list(keys)))
TypeError: sunion() takes at least 2 arguments (1 given); uid=631c2d625ee5726172cf67c6750de10a3e1a04bcd603bc9ad6d6b196fa8257a6; errno=None; agent=HTTPie/0.9.2; authn_type=BasicAuth; collection_id=bucket; collection_timestamp=1436354267425
```

**Comment by Natim** [comment]
We have the same problem with the postgresql backend.

This PR is probably going to fix this: https://github.com/mozilla-services/cliquet/pull/361

**Comment by Natim** [comment]
- [ ] Update the Kinto loadtest when fixing this - https://github.com/mozilla-services/kinto/blob/118-test-tutorial/loadtests/loadtest/tutorial.py#L301

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/cliquet/pull/361 and https://github.com/mozilla-services/cliquet/pull/381
