### ISSUE TITLE
Header value is not an string

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/kinto#18]
With a redis backend, Python 3.4.0 and a GET /v0/collections/todo/records on an unexisting collectionm I get:

```
2015-03-10 17:37:57,990 ERROR [waitress][Dummy-5] Exception when serving /v0/collections/todo/records
Traceback (most recent call last):
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/waitress-0.8.9-py3.4.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/waitress-0.8.9-py3.4.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/waitress-0.8.9-py3.4.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/pyramid-1.5.4-py3.4.egg/pyramid/router.py", line 243, in __call__
    return response(request.environ, start_response)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/response.py", line 1021, in __call__
    start_response(self.status, headerlist)
  File "/Users/tarek/Dev/github.com/kinto/.venv/lib/python3.4/site-packages/waitress-0.8.9-py3.4.egg/waitress/task.py", line 376, in start_response
    'Header value %r is not a string in %r' % (v, (k, v))
AssertionError: Header value b'1426005477988' is not a string in ('Last-Modified', b'1426005477988')
```
There's a type confusion

**Comment by tarekziade** [comment]
It looks like the headers values should be in string, not binary.

In https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource.py#L110 and followingm by removing the encoding and keeping the string, it works

does that sound right ?

**Comment by Natim** [comment]
Related to https://github.com/Pylons/waitress/issues/91
Not sure of how to fix waitress with this.

**Comment by Natim** [comment]
I continued to investigate this issue.

The result is that with Python2 is waiting for bytes and with Python3 for unicode strings.
It looks like a bug to me since it make us do unwanted conditions to handle both cases. I am not sure of how I can reach out to waitress and webob devs to fix this.
